server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.2.151:2181

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource           #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            #Mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vegedog.springcloud.entities   #所有Entity别名类所在包