server:
  port: 3344

spring:
  application:
    name:  cloud-config-center  #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #SSH地址：git@github.com:doufuchaorou/cloud2020-config.git会报错 应该与IDEA的某些配置有关
          uri: https://github.com/doufuchaorou/cloud2020-config.git #GitHub上面的git仓库名字，此处为HTTPS地址
          search-paths:
            - cloud2020-config
      label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#rabbitmq相关配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'